version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  science-blog:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  tailwindcss:
    build: .
    volumes:
      - .:/myapp
    env_file:
      - .env
    depends_on:
      - db
